### ISSUE TITLE
Squid spec v0.3

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/squid-java#102]
Related with https://github.com/oceanprotocol/ocean/issues/298 : 

- [x] Get list of the Assets Published by an user
- [x] Get list of the Assets Purchased by an user
- [x] Get the SEA status
- [x] Get the Owner of an Asset
- [x] Expose an additional consume interface allowing to use index parameter
- [x] Consumer can initialize a SEA on-chain
- [x] Validate an Asset Data integrity

**Comment by aaitor** [comment]
@eruizgar91 can you update the state of this one please?
