### ISSUE TITLE
Vulnerability in squid-java 0.4.4

### ISSUE THREAD

**Issue by AyushVerma2** [oceanprotocol/squid-java#105]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository.

## Expected Behavior

Please describe the behavior you are expecting
I believe there should not be any at least HIGH SEVERITY Vulnerability in squid-java

## Current Behavior

What is the current behavior? Please provide as many details as possible.
There are lots of Vulnerability whose severity is high.
## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Step to Reproduce the problem
I added snyk plugin snyk in my  IntelliJ IDE and run the tool over starfish-java pom, and find the below report. 
Please provide detailed steps for reproducing the issue.

1.
2.
3.

### Possible Solution

Fill this section in if you know how this could or should be fixed.
Need to upgrade few libraries with a new version which doesn't have a vulnerability.
## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: x.x.x
* Java: 1.8
* Barge: x.x.x
* OS: macOS/linux/win

## Failure Logs

Please include any relevant log snippets or files here.

[squid-java-vulnerability-issue.docx](https://github.com/oceanprotocol/squid-java/files/3161009/squid-java-vulnerability-issue.docx)

**Comment by kremalicious** [comment]
Current version is `v0.5.3`, please reopen if vulnerabilities are still present. Also, `starfish-java pom` seems like another project, not this one here
