### ISSUE TITLE
Configuration to access Nile testnet

### ISSUE THREAD

**Issue by adonnini** [oceanprotocol/squid-java#126]
I am trying to use squid-java in my Android app to post and retrieve metadata from Nile testnet.

Sorry for all these questions. I thought it would be better to try and ask them all at once rather piecemeal.

The first issue I am trying to deal with is how to change the configuration to access Nile testnet.

I looked through the test files, and ocean-cli source code.

As I understand it, I need to modify application.conf in resources/ using values from:
https://docs.oceanprotocol.com/concepts/testnets/#ocean-components-connected-to-nile
and
https://github.com/oceanprotocol/commons/blob/master/client/.env.local.example
Is this correct?

Do I need a resources/networks/niletestnet.conf created by modifying
 ocean-cli/src/main/resources/networks/spree.conf 
?

Is the value of keeper.url for accessing Nile testnet
https://nile.dev-ocean.com/ 
?

Would you advise  that I use TypeSafe or the Properties class to set the value of configuration parameters for the application?

Do I need a metada.json file, or can I create the value of metada in my application, as I currently do when accessing the Bigchaindb test net?

Initially, all I want to do is distribute and retrieve metada. Would I use 
 squid-java/src/test/java/com/oceanprotocol/squid/api/AssetsApiIT.java 
as my template/starting point?

Thanks,

Alex Donnini

**Comment by josepablofm78** [comment]
Hi Alex,
Thanks for give squid-java a try. We really appreciate it.
I will try to answer your questions:

- In order to connect with Nile you need to provide an application.conf file with the URLs and the addresses of Nile testnet. This configuration file should be in your classpath (unless you are using TypeSafe, as I will explane later)

- We are aware that the README content could be confusing and it does not explain how to connect to the testnets. We will try to fix this situation. In the meantime, I will show you in the next comment a template of the configuration needed to use Nile

- The use of TypeSafe or the standard java’s Properties is up to you. For us, TypeSafe is more handy and convenience.  For instance, you can have the application.conf file anywhere on your device, and simply indicate this location to TypeSafe as an option of the JVM:
		-Dconfig.file=/path/to/nile-application.conf
 If you set your configuration with:
		config = ConfigFactory.load();
TypeSafe will take care of loading and parsing the file you set in the option of the JVM.
But if you feel more comfortable using Java’s Properties there is nothing wrong about it. We provide both options to facilitate the integration with different products or projects.
	
  - You can use the AssetMetadata object directly. We use a metadata json file in the tests because we feel is less error-prone.  As you can see in the setup of the AssetsApiIT, we use a DDO.fromJSON method to instantiate the AssetMetadata object. That means Jackson library will parse the json file and it will complain is something is wrong.

- Exactly, the create test is what you need to start with. The create method registers an asset into ocean (meaning register the DID on-chain on Keeper Contracts and the metadata on Aquarius). 
The resolve method retrieve the DDO’s content from Aquarius

I hope this explanation will be helpful to solve your doubts.  Don’t hesitate to write us back if you have any questions.

**Comment by josepablofm78** [comment]
keeper.url="https://nile.dev-ocean.com"
keeper.gasLimit=4712388
keeper.gasPrice=100000000000
keeper.tx.attempts=50
keeper.tx.sleepDuration=1000

aquarius.url="https://nginx-aquarius.dev-ocean.com"
# Used in the internal communications between Docker containers (Spree network)
aquarius-internal.url="https://nginx-aquarius.dev-ocean.com"
brizo.url="https://nginx-brizo.dev-ocean.com"

secretstore.url="https://secret-store.dev-ocean.com"

provider.address="0x376817c638d2a04f475a73af37f7b51a2862d567"

# Contracts addresses (Nile keeper-contracts v0.10.3)
contract.SignCondition.address="0x5a4301F8a7a8A13485621b9B4C82B1E66c112ee2"
contract.HashLockCondition.address="0xB5f2e45e8aD4a1339D542f2defd5095B98054590"
contract.LockRewardCondition.address="0xE30FC30c678437e0e8F78C52dE9db8E2752781a0"
contract.AccessSecretStoreCondition.address="0x45DE141F8Efc355F1451a102FB6225F1EDd2921d"
contract.EscrowReward.address="0xeD4Ef53376C6f103d2d7029D7E702e082767C6ff"
contract.EscrowAccessSecretStoreTemplate.address="0xfA16d26e9F4fffC6e40963B281a0bB08C31ed40C"
contract.OceanToken.address="0x9861Da395d7da984D5E8C712c2EDE44b41F777Ad"
contract.Dispenser.address="0x865396b7ddc58C693db7FCAD1168E3BD95Fe3368"
contract.DIDRegistry.address="0x4A0f7F763B1A7937aED21D63b2A78adc89c5Db23"
contract.ConditionStoreManager.address="0x39b0AA775496C5ebf26f3B81C9ed1843f09eE466"
contract.TemplateStoreManager.address="0x9768c8ae44f1dc81cAA98F48792aA5730cAd2F73"
contract.AgreementStoreManager.address="0x62f84700b1A0ea6Bfb505aDC3c0286B7944D247C"

consume.basePath = "/tmp"

## Main account
account.main.address="0x...."
account.main.password="..."
account.main.credentialsFile="/path/to/credentials.json"

**Comment by adonnini** [comment]
Hi Jose'

My current plan is to modify AssetsApiIT.java for use in my application, and then call the setUp() and create() methods to publish metadata onto Nile testne.

One of the changes I plan on making is to replace

        metadataBase = DDO.fromJSON(new TypeReference<AssetMetadata>() {
        }, METADATA_JSON_CONTENT);
with
      metadataBase = AssetMetadata.builder();
      metadataBase.base.name = "test001";
//Plus values for other fields in Base, Curation and File

In fact, I may remove the assignment of value to metadataBase from setUp(), and add it to the class in my application where I will process Ocean Protocol transactions

Does this sound OK?

By the way, which of the fields in Base, Curation and File are mandatory?

Thanks,

Alex

**Comment by adonnini** [comment]
Hi Jose',
I added the modified AssetsApiIT.java to my code.

I am having trouble with these two import statements:

import com.oceanprotocol.keeper.contracts.EscrowAccessSecretStoreTemplate;
import com.oceanprotocol.keeper.contracts.TemplateStoreManager;

I looked through the squid-java source code on GitHub and could not find the 
com.oceanprotocol.keeper.contracts
or
com.oceanprotocol.keeper
locations. I feel like I ma missing something obvious...

Thanks,

Alex

**Comment by adonnini** [comment]
Hi,

Other imports I am having problems locating:

import com.oceanprotocol.secretstore.core.EvmDto;
import com.oceanprotocol.secretstore.core.SecretStoreDto;

these like the other two I mentioned in my previous post, and probably others I will find later, do not appear to be in the squid root directory.

Frankly, I am a little lost.

Thanks

**Comment by adonnini** [comment]
Items like
EscrowAccessSecretStoreTemplate
TemplateStoreManager

are written in Solidity, right?

I found them in 
keeper-contracts/contracts/templates/

Do I just need to add to my app a package (com.oceanprotocol.keeper.contracts)  containing the necessary files from keeper-contracts?

I could not find 
EvmDto
SecretStoreDto

Sorry about the barrage of posts.

**Comment by josepablofm78** [comment]
Hi Alex,

those classes are spread along two ocean's repositories, secret-store-client and keeper-contracts.

if you are using maven, these libraries should be imported automatically, but if you are importing the dependencies manually, you can download the jars here:

https://mvnrepository.com/artifact/com.oceanprotocol/secret-store-client
https://mvnrepository.com/artifact/com.oceanprotocol/keeper-contracts

**Comment by josepablofm78** [comment]
> Items like
> EscrowAccessSecretStoreTemplate
> TemplateStoreManager
> 
> are written in Solidity, right?
> 

These classes are java stubs generated by a web3j maven plugin.  It's not the contracts itself but utility classes to interact with the smart contracts

**Comment by adonnini** [comment]
Thanks for your help Jose'

**Comment by adonnini** [comment]
Hi Jose',
I am afraid I have some bad news (at least bad for me). Android currently does not support Java 11. I can't use squid-java as is. 
Read.md states that Java 11 is required, no point in trying to rebuild with Java 8, right?
Thanks,
Alex

**Comment by josepablofm78** [comment]
Hi Alex, 

you could try to compile the sources using maven and java 8. You would need to modify the pom.xml file, to configure the maven compiler properly.

I would say you just need to change the definition of maven-compiler-plugin to this:

 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
  </plugin>

**Comment by adonnini** [comment]
Hi Jose',

As usual, your response is very helpful.

I was hoping you would suggest that I recompile using Java 8!

Thanks,

Alex

**Comment by adonnini** [comment]
Hi Jose',

I was able to recompile squid-java using Java 1.8. I needed to make just a couple of small source code changes.

However, building my app with the addition of squid-java is not working. There are several errors all related to the gradle build process in Android Studio. I have used the latest gradle version and android gradle plugin without success (and several other combinations of gradle/android plugin versions). The issues are all related to dependencies in squid-java, I believe.

Please let me know if you have any thoughts as to how I could go about resolving these issues. I would be glad to provide you with any additional information. Below, you will find the build output.

I have a few more things I plan on trying to resolve the issues.

build failed	32s 555ms
Run build	32s 453ms
Load build	1ms
Configure build	26ms
Calculate task graph	192ms
Run tasks	32s 225ms
null	
The following project options are deprecated and have been removed:	
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.	
The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.0.	
The following project options are deprecated and have been removed:	
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.	
/home/adonnini1/Development/workspaceLunaADT/ContextQ-Android-app	
com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/adonnini1/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.11.1/592a48674c926b01a9a747c7831bcd82a9e6d6e4/log4j-core-2.11.1.jar	
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.	
com.android.tools.r8.CompilationFailedException: Compilation failed to complete	
com.android.tools.r8.utils.AbortException: Error: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)	
null	
/home/adonnini1/Development/workspaceLunaADT/ContextQ-Android-app	
libs/google-api-client-1.26.0.jar	
Type `com.google.common.base.Splitter` was not found, it is required for default or static interface methods desugaring of `java.util.Map com.google.api.client.googleapis.testing.TestUtils.parseQuery(java.lang.String)`	
Type `com.google.common.collect.Lists` was not found, it is required for default or static interface methods desugaring of `java.util.Map com.google.api.client.googleapis.testing.TestUtils.parseQuery(java.lang.String)`	
Type `com.google.api.client.auth.oauth2.BearerToken` was not found, it is required for default or static interface methods desugaring of `void com.google.api.client.googleapis.auth.oauth2.GoogleCredential$Builder.<init>()`	
Type `com.google.api.client.auth.oauth2.Credential$Builder` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleCredential$Builder com.google.api.client.googleapis.auth.oauth2.GoogleCredential$Builder.setTransport(com.google.api.client.http.HttpTransport)`	
Type `com.google.api.client.auth.openidconnect.IdTokenVerifier$Builder` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier$Builder com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier$Builder.setIssuer(java.lang.String)`	
Type `com.google.api.client.auth.openidconnect.IdTokenVerifier` was not found, it is required for default or static interface methods desugaring of `boolean com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier.verify(com.google.api.client.googleapis.auth.oauth2.GoogleIdToken)`	
Type `com.google.api.client.auth.oauth2.BrowserClientRequestUrl` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleBrowserClientRequestUrl com.google.api.client.googleapis.auth.oauth2.GoogleBrowserClientRequestUrl.setResponseTypes(java.util.Collection)`	
Type `com.google.api.client.auth.oauth2.Credential` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleCredential com.google.api.client.googleapis.auth.oauth2.GoogleCredential.setAccessToken(java.lang.String)`	
Type `com.google.api.client.auth.oauth2.AuthorizationCodeTokenRequest` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.setRequestInitializer(com.google.api.client.http.HttpRequestInitializer)`	
Type `com.google.api.client.auth.oauth2.TokenResponse` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleTokenResponse com.google.api.client.googleapis.auth.oauth2.GoogleTokenResponse.setAccessToken(java.lang.String)`	
Type `com.google.api.client.auth.oauth2.BearerToken` was not found, it is required for default or static interface methods desugaring of `void com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow$Builder.<init>(com.google.api.client.http.HttpTransport, com.google.api.client.json.JsonFactory, java.lang.String, java.lang.String, java.util.Collection)`	
Type `com.google.api.client.auth.oauth2.AuthorizationCodeFlow$Builder` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow$Builder com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow$Builder.setDataStoreFactory(com.google.api.client.util.store.DataStoreFactory)`	
Type `com.google.api.client.auth.openidconnect.IdToken` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleIdToken$Payload com.google.api.client.googleapis.auth.oauth2.GoogleIdToken.getPayload()`	
Type `com.google.api.client.auth.openidconnect.IdToken$Payload` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleIdToken$Payload com.google.api.client.googleapis.auth.oauth2.GoogleIdToken$Payload.setAuthorizationTimeSeconds(java.lang.Long)`	
Type `com.google.api.client.auth.oauth2.BearerToken` was not found, it is required for default or static interface methods desugaring of `void com.google.api.client.googleapis.compute.ComputeCredential$Builder.<init>(com.google.api.client.http.HttpTransport, com.google.api.client.json.JsonFactory)`	
Type `com.google.api.client.auth.oauth2.Credential$Builder` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.compute.ComputeCredential$Builder com.google.api.client.googleapis.compute.ComputeCredential$Builder.setTransport(com.google.api.client.http.HttpTransport)`	
Type `com.google.api.client.auth.oauth2.AuthorizationCodeRequestUrl` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeRequestUrl com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeRequestUrl.setResponseTypes(java.util.Collection)`	
Type `com.google.api.client.auth.oauth2.RefreshTokenRequest` was not found, it is required for default or static interface methods desugaring of `com.google.api.client.googleapis.auth.oauth2.GoogleRefreshTokenRequest com.google.api.client.googleapis.auth.oauth2.GoogleRefreshTokenRequest.setRequestInitializer(com.google.api.client.http.HttpRequestInitializer)`	
libs/javautil-3.1.1.jar	
libs/slf4j-api-1.7.7.jar	
../../../.gradle/caches/modules-2/files-2.1/com.typesafe/config/1.3.4/d0b3799b8e3a65c7b58c2aab9963603e687e2f91/config-1.3.4.jar	
../../../.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.9.8/11283f21cc480aa86c4df7a0a3243ec508372ed2/jackson-databind-2.9.8.jar	
../../../.gradle/caches/modules-2/files-2.1/javax.xml.bind/jaxb-api/2.3.0/99f802e0cb3e953ba3d6e698795c4aeb98d37c48/jaxb-api-2.3.0.jar	
../../../.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.11.1/592a48674c926b01a9a747c7831bcd82a9e6d6e4/log4j-core-2.11.1.jar	
../../../.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.11.1/268f0fe4df3eefe052b57c87ec48517d64fb2a10/log4j-api-2.11.1.jar	
../../../.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-posix/3.0.33/86dd65d4c33c4a6c8c260ee256bfcfecd8c45bee/jnr-posix-3.0.33.jar	
Interface `okhttp3.internal.tls.TrustRootIndex(classpath class)` used as super class of `okhttp3.internal.tls.TrustRootIndex$AndroidTrustRootIndex`.	
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)	
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)	
Interface `okhttp3.internal.tls.TrustRootIndex(classpath class)` used as super class of `okhttp3.internal.tls.TrustRootIndex$AndroidTrustRootIndex`.

**Comment by adonnini** [comment]
Hi Jose'
I would still like to know whether there is an updated application.conf file.
However, I think the error above has nothing to do with any changes you may have made.
Thanks,
Alex

**Comment by adonnini** [comment]
Hi Jose',

I worked around the issue using Java Properties instead of typesafe.

Now, OceanAPI initialization fails telling me that I have the incorrect password.

In your samplae above, if I understood you correctly, you said:

"You just need to set the data relative with the main account"

I never set up an account. I am not sure what you mean. With the bigchaindb java driver, I can set the password programatically. Can I do that with squid-java? How?

I am a little lost on this one. I hope you can help me.

Thanks,

Alex

**Comment by adonnini** [comment]
Hi Jose',

Where can I find an example of this

account.main.credentialsFile="/path/to/credentials.json"

Thanks,

Alex
