### ISSUE TITLE
Nile Testnet configuration clarification

### ISSUE THREAD

**Issue by adonnini** [oceanprotocol/squid-java#139]
In other issues, when asked for configuration for the Nile testnet, you send a copy of the application.conf file.

Using it as is does not work. Probably this is due my misunuderstanding.

Below is the file you send.

I assume that the lines

account.main.address="0x...."
account.main.password="..."
account.main.credentialsFile="/path/to/credentials.json"

are stand-ins

Do we get main.address from the parity folder? If not, where from?
Do we set the password to any value we like?
What is the default /path/to/credentials.json?

In AssetsApiIT.java, when properties are defined, the definition includes these three lines:
        properties.put(OceanConfig.MAIN_ACCOUNT_ADDRESS, config.getString("account.parity.address2"));
        properties.put(OceanConfig.MAIN_ACCOUNT_PASSWORD, config.getString("account.parity.password2"));
        properties.put(OceanConfig.MAIN_ACCOUNT_CREDENTIALS_FILE, config.getString("account.parity.file2"));

I found no other mention of account.parity.address2, account.parity.password2, and account.parity.file2
Where can they be found?

Thank you,

Alex Donnini

application.conf for Nile testnet
---------------------------------------
keeper.url="https://nile.dev-ocean.com"
keeper.gasLimit=4712388
keeper.gasPrice=100000000000
keeper.tx.attempts=50
keeper.tx.sleepDuration=1000

aquarius.url="https://aquarius.commons.oceanprotocol.com"
aquarius-internal.url="https://aquarius.commons.oceanprotocol.com"
brizo.url="https://nginx-brizo.dev-ocean.com"
secretstore.url="https://secret-store.dev-ocean.com"

provider.address="0x376817c638d2a04f475a73af37f7b51a2862d567"

contract.SignCondition.address="0x5a4301F8a7a8A13485621b9B4C82B1E66c112ee2"
contract.HashLockCondition.address="0xB5f2e45e8aD4a1339D542f2defd5095B98054590"
contract.LockRewardCondition.address="0xE30FC30c678437e0e8F78C52dE9db8E2752781a0"
contract.AccessSecretStoreCondition.address="0x45DE141F8Efc355F1451a102FB6225F1EDd2921d"
contract.EscrowReward.address="0xeD4Ef53376C6f103d2d7029D7E702e082767C6ff"
contract.EscrowAccessSecretStoreTemplate.address="0xfA16d26e9F4fffC6e40963B281a0bB08C31ed40C"
contract.OceanToken.address="0x9861Da395d7da984D5E8C712c2EDE44b41F777Ad"
contract.Dispenser.address="0x865396b7ddc58C693db7FCAD1168E3BD95Fe3368"
contract.DIDRegistry.address="0x4A0f7F763B1A7937aED21D63b2A78adc89c5Db23"
contract.ConditionStoreManager.address="0x39b0AA775496C5ebf26f3B81C9ed1843f09eE466"
contract.TemplateStoreManager.address="0x9768c8ae44f1dc81cAA98F48792aA5730cAd2F73"
contract.AgreementStoreManager.address="0x62f84700b1A0ea6Bfb505aDC3c0286B7944D247C"

consume.basePath = "/tmp"

account.main.address="0x...."
account.main.password="..."
account.main.credentialsFile="/path/to/credentials.json"

**Comment by kremalicious** [comment]
Sorry for the confusion, the configuration of this library definitely could use [some improvements](https://github.com/oceanprotocol/squid-java/issues/123).

From a quick look, the provided urls are outdated and mix Nile & Pacific urls. These are the components currently deployed in Nile: https://docs.oceanprotocol.com/concepts/testnets/#ocean-components-connected-to-nile

The `provider.address` for Nile should be `0x4aaab179035dc57b35e2ce066919048686f82972`.

The contract addresses for Nile you could get from the Commons installation in Nile shown under Brizo or Squid-js: https://commons.nile.dev-ocean.com/about

For the rest, @josepablofm78 probably has more insights.

**Comment by adonnini** [comment]
Thanks @kremalicious this is helpful.
The key question I hope Jose' can help answer is the value of the following:

account.main.address="0x...."
account.main.password="..."
account.main.credentialsFile="/path/to/credentials.json"

Thanks

**Comment by josepablofm78** [comment]
hi alex,
the account.main.xxx properties are used to configure the account you want to use to interact with squid, like publish or consume assets. 

So you must set the values of an account of your own.

regarding the question you have about  properties like account.parity.address2, that's additional configuration for the integration test. you don't need to set these properties to use squid's API

**Comment by adonnini** [comment]
Hi Jose',
Thanks for getting back to me.
I am uncertain as to what you mean when you say

"So you must set the values of an account of your own."

do you mean just give a value to the account parameters like this?

        properties.put(OceanConfig.MAIN_ACCOUNT_ADDRESS, "0x068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0");
        properties.put(OceanConfig.MAIN_ACCOUNT_PASSWORD, "secret");
        properties.put(OceanConfig.MAIN_ACCOUNT_CREDENTIALS_FILE, "/data/data/com.android.contextq/resources/accounts/parity/068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0.json.testaccount");

Except for the password, I took the values from the parity folder in squid-java/src/test/resources/accounts/parity

However, clearly this approach does not work, should it?

I am sorry for being slow. Could you give me an example of what you mean by:

"So you must set the values of an account of your own."?

So far, I have been able to figure things out on my own, and get squid-java to work under Android without documentation.

I would appreciate your help on this.

Thanks,

Alex

**Comment by josepablofm78** [comment]
hi,

that would be a correct example of configuration, but I guess the 0x068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0 account is not valid in nile.

So what you need is to have, or create, an ethereum account owned by you. And you would need the address, password and credentials file of this account.

Also, you might have to get ether to use your account  in Nile.

For this, you can use the faucet deployed in Nile: https://faucet.nile.dev-ocean.com/

(Faucet's API especification in https://github.com/oceanprotocol/faucet)

Or you can follow the instructions to use metamask for the same purpose:
https://blog.oceanprotocol.com/the-commons-data-marketplace-c57a44288314 (See "SetUp MetaMask and get some Ether for Nile")

**Comment by adonnini** [comment]
Thanks for the quick repsonse Jose'.

So, there is no way to be a data publisher/retriever without having an ether account? That's pretty restrictive.

Thanks,

Alex

**Comment by adonnini** [comment]
Hi Jose',

I reread your message above. 

When you say 

"you might have to get ether to use your account in Nile."

do you mean I have to get ether, or I don't have to get ether? I am sorry but "might" is very vague. If you do not know, could you point me to someone who would know?

Thanks,

Alex

**Comment by josepablofm78** [comment]
you need balance for the gas of the transactions, and also to consume an asset if the price is greater than 0.

some tips about the credentials file:

https://ethereum.stackexchange.com/questions/16797/export-metamask-account-to-json-file

https://ethereum.stackexchange.com/questions/37524/generate-keystore-file-from-raw-private-key-using-geth

https://ethereum.stackexchange.com/questions/16797/export-metamask-account-to-json-file
