### ISSUE TITLE
Insufficient funds exception

### ISSUE THREAD

**Issue by adonnini** [oceanprotocol/squid-java#142]
Hi Jose',

I set up an ethereum account/wallet, created a credentials file via geth, and placed it in resurces/accounts/ganache

Below you will find the error log posted by the application.

I think the transaction failed because of insufficient funds in the account. Is this right?

I am puzzled by the fact that it seems that I would need a high balance: "Required 31415916858408"

What do you think?

Thanks,

Alex

08-07 12:28:10.464: W/System.err(1415): ERROR AccountsManager Unable request tokens 1: Error processing transaction request: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 31415916858408 and got: 0.
08-07 12:28:10.465: W/System.err(1415): com.android.squid.exceptions.EthereumException: Unable request tokens 1
08-07 12:28:10.466: W/System.err(1415): 	at com.android.squid.manager.AccountsManager.requestTokens(AccountsManager.java:144)
08-07 12:28:10.466: W/System.err(1415): 	at com.android.squid.api.impl.TokensImpl.request(TokensImpl.java:31)
08-07 12:28:10.466: W/System.err(1415): 	at com.android.contextq.locationestimation.OceanProtocolLocationEstimation.setUp(OceanProtocolLocationEstimation.java:336)
08-07 12:28:10.466: W/System.err(1415): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1718)
08-07 12:28:10.466: W/System.err(1415): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1703)
08-07 12:28:10.466: W/System.err(1415): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-07 12:28:10.466: W/System.err(1415): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-07 12:28:10.466: W/System.err(1415): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-07 12:28:10.466: W/System.err(1415): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-07 12:28:10.466: W/System.err(1415): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-07 12:28:10.466: W/System.err(1415): 	at java.lang.Thread.run(Thread.java:764)
08-07 12:28:10.467: W/System.err(1415): Caused by: java.lang.RuntimeException: Error processing transaction request: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 31415916858408 and got: 0.
08-07 12:28:10.467: W/System.err(1415): 	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:72)
08-07 12:28:10.467: W/System.err(1415): 	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:52)
08-07 12:28:10.468: W/System.err(1415): 	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:88)
08-07 12:28:10.468: W/System.err(1415): 	at org.web3j.tx.Contract.executeTransaction(Contract.java:291)
08-07 12:28:10.468: W/System.err(1415): 	at org.web3j.tx.Contract.executeTransaction(Contract.java:275)
08-07 12:28:10.468: W/System.err(1415): 	at org.web3j.tx.Contract.executeTransaction(Contract.java:269)
08-07 12:28:10.468: W/System.err(1415): 	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:321)
08-07 12:28:10.469: W/System.err(1415): 	at org.web3j.tx.-$$Lambda$Contract$w6-chY5FF2Qs682sB2cKs6onFiM.call(Unknown Source:4)
08-07 12:28:10.469: W/System.err(1415): 	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
08-07 12:28:10.469: W/System.err(1415): 	at com.android.squid.manager.AccountsManager.requestTokens(AccountsManager.java:140)
08-07 12:28:10.469: W/System.err(1415): 	... 10 more

08-07 12:28:11.720: W/System.err(1415): com.android.squid.exceptions.DDOException: Error registering Asset.
08-07 12:28:11.720: W/System.err(1415): 	at com.android.squid.manager.OceanManager.registerAsset(OceanManager.java:274)
08-07 12:28:11.721: W/System.err(1415): 	at com.android.squid.manager.OceanManager.registerAccessServiceAsset(OceanManager.java:217)
08-07 12:28:11.722: W/System.err(1415): 	at com.android.squid.api.impl.AssetsImpl.create(AssetsImpl.java:50)
08-07 12:28:11.722: W/System.err(1415): 	at com.android.squid.api.impl.AssetsImpl.create(AssetsImpl.java:55)
08-07 12:28:11.722: W/System.err(1415): 	at com.android.contextq.locationestimation.OceanProtocolLocationEstimation.create(OceanProtocolLocationEstimation.java:361)
08-07 12:28:11.722: W/System.err(1415): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1728)
08-07 12:28:11.722: W/System.err(1415): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1703)
08-07 12:28:11.722: W/System.err(1415): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-07 12:28:11.722: W/System.err(1415): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-07 12:28:11.723: W/System.err(1415): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-07 12:28:11.724: W/System.err(1415): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-07 12:28:11.724: W/System.err(1415): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-07 12:28:11.724: W/System.err(1415): 	at java.lang.Thread.run(Thread.java:764)
08-07 12:28:11.725: W/System.err(1415): Caused by: com.android.squid.exceptions.DIDRegisterException: Error registering DID d358406547b6450bb52deda7d12a6033c390c5d334e64918bad311133908dfe3
08-07 12:28:11.725: W/System.err(1415): 	at com.android.squid.manager.OceanManager.registerDID(OceanManager.java:177)
08-07 12:28:11.725: W/System.err(1415): 	at com.android.squid.manager.OceanManager.registerAsset(OceanManager.java:268)
08-07 12:28:11.726: W/System.err(1415): 	... 12 more
08-07 12:28:11.727: W/System.err(1415): Caused by: java.lang.RuntimeException: Error processing transaction request: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 31415916858408 and got: 0.
08-07 12:28:11.727: W/System.err(1415): 	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:72)
08-07 12:28:11.727: W/System.err(1415): 	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:52)
08-07 12:28:11.727: W/System.err(1415): 	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:88)
08-07 12:28:11.727: W/System.err(1415): 	at org.web3j.tx.Contract.executeTransaction(Contract.java:291)
08-07 12:28:11.728: W/System.err(1415): 	at org.web3j.tx.Contract.executeTransaction(Contract.java:275)
08-07 12:28:11.728: W/System.err(1415): 	at org.web3j.tx.Contract.executeTransaction(Contract.java:269)
08-07 12:28:11.729: W/System.err(1415): 	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:321)
08-07 12:28:11.729: W/System.err(1415): 	at org.web3j.tx.-$$Lambda$Contract$w6-chY5FF2Qs682sB2cKs6onFiM.call(Unknown Source:4)
08-07 12:28:11.729: W/System.err(1415): 	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
08-07 12:28:11.729: W/System.err(1415): 	at com.android.squid.manager.OceanManager.registerDID(OceanManager.java:172)
08-07 12:28:11.730: W/System.err(1415): 	... 13 more

**Comment by kremalicious** [comment]
Yes, this is the gas cost so you need to have Ether in your wallet. Every transaction in an Ethereum-based network requires Gas to execute transactions. The amount you see displayed for that in your error message is the Gas amount in vodka (like wei for Ethereum).

In Pacific, Nile, and other Ocean networks you can get Ether for free via a faucet. You can learn more about how to get Ether for the network you're using in the docs:
https://docs.oceanprotocol.com/tutorials/get-ether-and-ocean-tokens/

**Comment by adonnini** [comment]
Thanks very much @kremalicious 
I have already been getting Ether via Faucet. The maximum allowed (unless I did something wrong) is 0.05 ether per day. At present, I have 0.10 ether.

If that is sufficient, then something is not working in my code.

This is why I wanted confirmation that based on the error logs, the current issue is one of insufficient balance, and not something else too.

Thanks,

Alex

**Comment by adonnini** [comment]
I just checked with etherscan. The balance in my ether account is 0 although I added ether twice via Faucet (via Metamask)

**Comment by kremalicious** [comment]
You can simply convert vodka like you convert wei to figure out what you need to cover gas costs: https://etherconverter.online. So yes, 0.05 ETH are more than enough to simply cover Gas.

Etherscan only reflects Ethereum's main and testnet blockchain, NOT any Ocean network. So if you send yourself Ether in one of the Ocean networks there's no way for it to show up in Etherscan. Ocean has their own blockchain explorers for each network, please see https://docs.oceanprotocol.com/concepts/tools/#submarine-blockchain-explorer

**Comment by adonnini** [comment]
Thanks @kremalicious. 

This is a question for Jose' as it relates to squid-java.

If I have more than enough funds to cover Gas why did the app fail with

"08-07 12:28:10.464: W/System.err(1415): ERROR AccountsManager Unable request tokens 1: Error processing transaction request: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 31415916858408 and got: 0."

Thanks,

Alex

**Comment by kremalicious** [comment]
what is your account address? In what network did you send yourself Ether? What network do you connect to with squid-java?

The error message is really clear, the account you're using with squid-java does not have a balance. Question is why the account you say you sent Ether to seems to be not the one being used in squid-java

**Comment by adonnini** [comment]
Account address - 0xf2E58F180A0bE31cBeCA8b145e5258DDdadBe864

Network I connect to - Nile Testnet

Screenshot of faucet ether generation operation
![Screenshot from 2019-08-08 17-02-40](https://user-images.githubusercontent.com/28863649/62737964-19133900-b9ff-11e9-9ff7-2ba360e6c311.png)

Below you will find the latest error log generated by the application.

I must be doing something wrong. I cannot see it. Could the problem be that I generated the credentials file with geth? 

Thanks,

Alex


08-08 17:32:24.852: W/System.err(13648): ERROR AccountsManager Unable to get account(0xf2E58F180A0bE31cBeCA8b145e5258DDdadBe864) Ocean balance: Empty value (0x) returned from contract
08-08 17:32:24.853: W/System.err(13648): com.android.squid.exceptions.EthereumException: Unable to get account(0xf2E58F180A0bE31cBeCA8b145e5258DDdadBe864) Ocean balance
08-08 17:32:24.853: W/System.err(13648): 	at com.android.squid.manager.AccountsManager.getOceanAccountBalance(AccountsManager.java:124)
08-08 17:32:24.854: W/System.err(13648): 	at com.android.squid.manager.AccountsManager.getAccountBalance(AccountsManager.java:85)
08-08 17:32:24.854: W/System.err(13648): 	at com.android.squid.api.impl.AccountsImpl.balance(AccountsImpl.java:45)
08-08 17:32:24.854: W/System.err(13648): 	at com.android.contextq.locationestimation.OceanProtocolLocationEstimation.setUp(OceanProtocolLocationEstimation.java:338)
08-08 17:32:24.854: W/System.err(13648): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1718)
08-08 17:32:24.854: W/System.err(13648): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1703)
08-08 17:32:24.854: W/System.err(13648): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-08 17:32:24.854: W/System.err(13648): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-08 17:32:24.854: W/System.err(13648): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-08 17:32:24.854: W/System.err(13648): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-08 17:32:24.854: W/System.err(13648): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-08 17:32:24.854: W/System.err(13648): 	at java.lang.Thread.run(Thread.java:764)
08-08 17:32:24.854: W/System.err(13648): Caused by: org.web3j.tx.exceptions.ContractCallException: Empty value (0x) returned from contract
08-08 17:32:24.854: W/System.err(13648): 	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:246)
08-08 17:32:24.854: W/System.err(13648): 	at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1(Contract.java:313)
08-08 17:32:24.854: W/System.err(13648): 	at org.web3j.tx.-$$Lambda$Contract$oYGWABDpPbmg8SXDB6ogrDJA-Nw.call(Unknown Source:6)
08-08 17:32:24.854: W/System.err(13648): 	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
08-08 17:32:24.855: W/System.err(13648): 	at com.android.squid.manager.AccountsManager.getOceanAccountBalance(AccountsManager.java:120)
08-08 17:32:24.855: W/System.err(13648): 	... 11 more

08-08 17:32:30.745: W/System.err(13648): com.android.squid.exceptions.DDOException: Error registering Asset.
08-08 17:32:30.746: W/System.err(13648): 	at com.android.squid.manager.OceanManager.registerAsset(OceanManager.java:274)
08-08 17:32:30.746: W/System.err(13648): 	at com.android.squid.manager.OceanManager.registerAccessServiceAsset(OceanManager.java:217)
08-08 17:32:30.746: W/System.err(13648): 	at com.android.squid.api.impl.AssetsImpl.create(AssetsImpl.java:50)
08-08 17:32:30.746: W/System.err(13648): 	at com.android.squid.api.impl.AssetsImpl.create(AssetsImpl.java:55)
08-08 17:32:30.746: W/System.err(13648): 	at com.android.contextq.locationestimation.OceanProtocolLocationEstimation.create(OceanProtocolLocationEstimation.java:361)
08-08 17:32:30.747: W/System.err(13648): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1728)
08-08 17:32:30.747: W/System.err(13648): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1703)
08-08 17:32:30.747: W/System.err(13648): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-08 17:32:30.747: W/System.err(13648): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-08 17:32:30.747: W/System.err(13648): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-08 17:32:30.747: W/System.err(13648): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-08 17:32:30.748: W/System.err(13648): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-08 17:32:30.748: W/System.err(13648): 	at java.lang.Thread.run(Thread.java:764)
08-08 17:32:30.748: W/System.err(13648): Caused by: com.android.squid.exceptions.DDOException: Error building DDO from JSON
08-08 17:32:30.748: W/System.err(13648): 	at com.android.squid.external.AquariusService.createDDO(AquariusService.java:83)
08-08 17:32:30.748: W/System.err(13648): 	at com.android.squid.manager.OceanManager.registerAsset(OceanManager.java:271)
08-08 17:32:30.748: W/System.err(13648): 	... 12 more
08-08 17:32:30.749: W/System.err(13648): Caused by: com.android.squid.exceptions.DDOException: Unable to create DDO: HttpResponse{statusCode=400, body='[{"message":"Additional properties are not allowed ('name', 'description' were unexpected)","path":"base/files/0"}]
08-08 17:32:30.749: W/System.err(13648): ', charset='ISO-8859-1', contentLength=116}
08-08 17:32:30.749: W/System.err(13648): 	at com.android.squid.external.AquariusService.createDDO(AquariusService.java:76)
08-08 17:32:30.749: W/System.err(13648): 	... 13 more

**Comment by kremalicious** [comment]
Although you are not actually connected to Nile with MetaMask (the UI message is pretty clear: "Not connected to Nile network"...), for faucet action it shouldn't matter and your account indeed has a balance with Nile ETH ("POA") and OCEAN: https://submarine.nile.dev-ocean.com/address/0xf2e58f180a0be31cbeca8b145e5258dddadbe864/transactions

To me, it looks like squid-java is not able to get the account at all:

```
Unable to get account(0xf2E58F180A0bE31cBeCA8b145e5258DDdadBe864) Ocean balance: Empty value (0x) returned from contract
```

Did you double-check your config?

**Comment by adonnini** [comment]
Below is the section of my code where I define the configuration. I double checked it. I cannot find what could be wrong

        String keeperUrl="https://nile.dev-ocean.com";
        String keeperGasLimit="4712388";
        String keeperGasPrice="100000000000";
        String keeperTxAttempts="50";
        String keeperTxSleepDuration="1000";

        String aquariusUrl="https://nginx-aquarius.dev-ocean.com";
        String aquariusInternalUrl="https://nginx-aquarius.dev-ocean.com";
        String brizoUrl="https://nginx-brizo.dev-ocean.com";
        String secretstoreUrl="https://secret-store.dev-ocean.com";

           providerConfig = new ProviderConfig(consumeUrl, purchaseEndpoint, metadataUrl, secretStoreEndpoint, providerAddress);

        properties = new Properties();
        properties.put(OceanConfig.KEEPER_URL, "https://nile.dev-ocean.com");
        properties.put(OceanConfig.KEEPER_GAS_LIMIT, "4712388");
        properties.put(OceanConfig.KEEPER_GAS_PRICE, "100000000000");
        properties.put(OceanConfig.KEEPER_TX_ATTEMPTS, "50");
        properties.put(OceanConfig.KEEPER_TX_SLEEPDURATION, "1000");
        properties.put(OceanConfig.AQUARIUS_URL, "https://aquarius.nile.dev-ocean.com");
        properties.put(OceanConfig.SECRETSTORE_URL, "https://secret-store.dev-ocean.com");
        properties.put(OceanConfig.CONSUME_BASE_PATH, "/data/data/com.android.contextq/resources/tmp");
        properties.put(OceanConfig.MAIN_ACCOUNT_ADDRESS, "0xf2E58F180A0bE31cBeCA8b145e5258DDdadBe864");
        properties.put(OceanConfig.MAIN_ACCOUNT_PASSWORD, "12Geico91--");
        properties.put(OceanConfig.MAIN_ACCOUNT_CREDENTIALS_FILE, "/data/data/com.android.contextq/resources/accounts/parity/UTC--2019-08-05T19-08-01.736900004Z--f2e58f180a0be31cbeca8b145e5258dddadbe864.json");
        properties.put(OceanConfig.DID_REGISTRY_ADDRESS, "0x4A0f7F763B1A7937aED21D63b2A78adc89c5Db23");
        properties.put(OceanConfig.AGREEMENT_STORE_MANAGER_ADDRESS, "0x62f84700b1A0ea6Bfb505aDC3c0286B7944D247C");
        properties.put(OceanConfig.CONDITION_STORE_MANAGER_ADDRESS, "0x39b0AA775496C5ebf26f3B81C9ed1843f09eE466");
        properties.put(OceanConfig.LOCKREWARD_CONDITIONS_ADDRESS, "0xE30FC30c678437e0e8F78C52dE9db8E2752781a0");
        properties.put(OceanConfig.ESCROWREWARD_CONDITIONS_ADDRESS, "0xeD4Ef53376C6f103d2d7029D7E702e082767C6ff");
        properties.put(OceanConfig.ESCROW_ACCESS_SS_CONDITIONS_ADDRESS, "0xfA16d26e9F4fffC6e40963B281a0bB08C31ed40C");
        properties.put(OceanConfig.ACCESS_SS_CONDITIONS_ADDRESS, "0x45DE141F8Efc355F1451a102FB6225F1EDd2921d");
        properties.put(OceanConfig.TEMPLATE_STORE_MANAGER_ADDRESS, "0x9768c8ae44f1dc81cAA98F48792aA5730cAd2F73");
        properties.put(OceanConfig.TOKEN_ADDRESS, "0x9861Da395d7da984D5E8C712c2EDE44b41F777Ad");
        properties.put(OceanConfig.DISPENSER_ADDRESS, "0x865396b7ddc58C693db7FCAD1168E3BD95Fe3368");
        properties.put(OceanConfig.PROVIDER_ADDRESS, "0x4aaab179035dc57b35e2ce066919048686f82972");

**Comment by josepablofm78** [comment]
Configuration looks good to me...

What are you trying to do? I mean, are you executing integration tests or  code of your own?

**Comment by adonnini** [comment]
The code I used as a starting point was AssetsApiIT.java

I modified it to use only the Java Properties class with the values listed in my entry above.

in my version of AssetsApiIT.java, the line that triggers the failure is

            Balance balance = oceanAPIConsumer.getAccountsAPI().balance(oceanAPIConsumer.getMainAccount());

in setup()

The only change I made before the execution of the above line was to replace
oceanAPIConsumer.getTokensAPI().request(BigInteger.TEN);
with
oceanAPIConsumer.getTokensAPI().request(BigInteger.ONE);

the failure occurs in AccountsManager.java when

getOceanAccountBalance is run

This may not mean anything and may be a case of my misunderstanding, I noticed that neither in AccountsManager or BaseManager there is an import statement for OceanToken

**Comment by adonnini** [comment]
In my code, I commented out:

        oceanAPIConsumer.getTokensAPI().request(BigInteger.ONE);
//        oceanAPIConsumer.getTokensAPI().request(BigInteger.TEN);
            Balance balance = oceanAPIConsumer.getAccountsAPI().balance(oceanAPIConsumer.getMainAccount());

            Log.d(TAG, "Account " + oceanAPIConsumer.getMainAccount().address + " balance is: " + balance.toString());
//            log.debug("Account " + oceanAPIConsumer.getMainAccount().address + " balance is: " + balance.toString());

            boolean isTemplateApproved = templateManager.isTemplateApproved(escrowAccessSecretStoreTemplate.getContractAddress()).send();

            Log.d(TAG, "Is escrowAccessSecretStoreTemplate approved? " + isTemplateApproved);
//            log.debug("Is escrowAccessSecretStoreTemplate approved? " + isTemplateApproved);

and removed a change I had made to AssetMetadata.

Now the code runs to completion without errors. However, I am not sure it is actually working as it should. It reports the following:

08-10 09:16:17.722: D/OceanProtocolLocationEstimation(25877):  - create - (ddo.id == resolvedDDO.id) - false
08-10 09:16:17.722: D/OceanProtocolLocationEstimation(25877):  - create - (resolvedDDO.services.size() == 3) - true

**Comment by adonnini** [comment]
All set

08-10 10:15:02.818: D/OceanProtocolLocationEstimation(31608):  - create - ddo.id - did:op:9d61f514e6ba4a4baa182b6a0bfecff9fc49756698f64d96a098d4dc3895109c
08-10 10:15:02.818: D/OceanProtocolLocationEstimation(31608):  - create - resolvedDDO.id - did:op:9d61f514e6ba4a4baa182b6a0bfecff9fc49756698f64d96a098d4dc3895109c
08-10 10:15:02.818: D/OceanProtocolLocationEstimation(31608):  - create - (ddo.id.equalsIgnoreCase(resolvedDDO.id)) - true
08-10 10:15:02.818: D/OceanProtocolLocationEstimation(31608):  - create - (resolvedDDO.services.size() == 3) - true

I think there may be a bug in the code that accesses an account to retrieve information, e.g. balance. I am saying this because once I commented out the code to retrieve account balance the application ran to completion as expected

**Comment by adonnini** [comment]
Hi,
Could you please let me know if you think I am correct when I say that there may be a bug in the balance retrieval function as I mentioned above? I need to access the account information retrieval function, and currently can't.
Thanks
