### ISSUE TITLE
lockPayment fails when the Access Service Template is registered with squid-java

### ISSUE THREAD

**Issue by josepablofm78** [oceanprotocol/squid-java#67]
The order process doesn't work properly when the Access Service's template is registered using the SetUpServiceAgreement class. The lockPayment's transaction fails for some reason.

At this point, everything seems to work fine registering the template using squid-java

This behavior can be reproduced using Barge, squid-java 0.3.2 and keeper-contracts 0.6.12

**Comment by aaitor** [comment]
fixed using keeper 0.8.5
