### ISSUE TITLE
AccountsManagerTest requires a GPG key for document encryption test

### ISSUE THREAD

**Issue by tmarble** [oceanprotocol/squid-java#77]
## Expected Behavior

Running the integration tests as specified in the README...
```
mvn clean verify -P integration-test -B -V > integration-test-0314.log 2>&1 &
```
_or as close to what's in .travis.xml as possible:_
```
mvn install -P integration-test -Dgpg.skip -Dmaven.javadoc.skip=true -B -V > integration-test-0314.log 2>&1 &
```

Should pass as in [Travis](https://travis-ci.com/oceanprotocol/squid-java/builds/104447758) see line 6008

## Current Behavior

The AccountsManagerTest fails (causing all further tests including integration tests to not be run):
```
2019-03-14 12:59:53 DEBUG PublisherWorker:94 - EVM: Document encryption
2019-03-14 12:59:53 ERROR PublisherWorker:109 - Exception: Unable to register the document: null
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.522 s <<< FAILURE! - in com.oceanprotocol.squid.manager.BaseManagerTest
[ERROR] buildDDO(com.oceanprotocol.squid.manager.BaseManagerTest)  Time elapsed: 0.311 s  <<< ERROR!
com.oceanprotocol.squid.exceptions.DDOException: Error building DDO
	at com.oceanprotocol.squid.manager.BaseManagerTest.buildDDO(BaseManagerTest.java:93)
Caused by: com.oceanprotocol.squid.exceptions.EncryptionException: Error encrypting Document
	at com.oceanprotocol.squid.manager.BaseManagerTest.buildDDO(BaseManagerTest.java:93)
Caused by: java.io.IOException: Unable to encrypt document
	at com.oceanprotocol.squid.manager.BaseManagerTest.buildDDO(BaseManagerTest.java:93)

[ERROR] buildDDOWithAuthorizationService(com.oceanprotocol.squid.manager.BaseManagerTest)  Time elapsed: 0.043 s  <<< ERROR!
com.oceanprotocol.squid.exceptions.DDOException: Error building DDO
	at com.oceanprotocol.squid.manager.BaseManagerTest.buildDDOWithAuthorizationService(BaseManagerTest.java:109)
Caused by: com.oceanprotocol.squid.exceptions.EncryptionException: Error encrypting Document
	at com.oceanprotocol.squid.manager.BaseManagerTest.buildDDOWithAuthorizationService(BaseManagerTest.java:109)
Caused by: java.io.IOException: Unable to encrypt document
	at com.oceanprotocol.squid.manager.BaseManagerTest.buildDDOWithAuthorizationService(BaseManagerTest.java:109)

[INFO] Running com.oceanprotocol.squid.manager.AccountsManagerTest
2019-03-14 12:59:53 DEBUG AccountsManagerTest:47 - Setting Up DTO's
2019-03-14 12:59:53 DEBUG AquariusService:40 - Getting Aquarius instance: http://localhost:5000
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.643 s - in com.oceanprotocol.squid.manager.AccountsManagerTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BaseManagerTest.buildDDO:93 » DDO Error building DDO
[ERROR]   BaseManagerTest.buildDDOWithAuthorizationService:109 » DDO Error building DDO
```

## Failure Information (for bugs)

Travis actually specifies an [additional maven settings file](https://github.com/oceanprotocol/squid-java/blob/develop/.maven.xml)

Which refers to environment variables [set in Travis](https://travis-ci.com/oceanprotocol/squid-java/settings)

Obviously running with the [full Travis arguments](https://github.com/oceanprotocol/squid-java/blob/develop/.travis.yml#L36) will fail without these environment variables set.

HOWEVER there is no mention of a requirement to set **GPG_PASSPHRASE** (or any of the other environment variables like **GPG_SECRET_KEYS**).

**NOTE ALSO** there are no contracts?
```
tmarble@cerise 127 :) ls -ls /home/tmarble/.ocean/keeper-contracts/artifacts
total 0
0 -rw-r--r-- 1 tmarble users 0 Mar 14 12:45 ready
tmarble@cerise 128 :)
```
Which causes `src/test/resources/scripts/updateConfAddresses.sh` to fail

## Step to Reproduce the problem

Try to run integration tests one of the two ways specified above.

### Possible Solution

Perhaps the README could be augmented with an explanation of how to create proper GPG key such that the required environment variables can be set such that all the tests will pass **OR** the document encryption tests should be off by default.

If contracts are, in fact, required some explanation in the README should me made about
verifying that there are contracts placed in the proper directory and running  `src/test/resources/scripts/updateConfAddresses.sh` .

## Specifications

* Version: `commit 2ff00b22eb38f370672065e2ceda2afe03aa5016 (HEAD -> develop, origin/develop, origin/HEAD)`
* Java: `openjdk version "1.8.0_191"`
* Barge: `commit c5e2e1591c26e8f6400caa536e6cfb6d8a8bb398 (HEAD -> develop, origin/develop, origin/HEAD)`
* OS: `Linux cerise 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux`

**Comment by aaitor** [comment]
From the README:
```
You can execute the integration tests using the following command:
mvn clean verify -P integration-test
```
The GPG key is needed for Travis but not for running the IT in local.
Looks your error is related with a problem starting `barge`. Starting `barge` in a fresh local environment (please prune your docker images to avoid having old versions) and in Travis works.

In any case, I added some additional details regarding the `updateConfAddresses.sh` script.
