### ISSUE TITLE
Integration tests failing and not detected by Travis

### ISSUE THREAD

**Issue by tmarble** [oceanprotocol/squid-java#95]
## Expected Behavior

Running all the tests (both unit and integration tests) per the README should pass.

## Current Behavior

1. The README has a typo (2 occurrences) in specifying "all-test" when it should be "all-tests"
`mvn clean verify -P all-test`
See the [pom.xml](https://github.com/oceanprotocol/squid-java/blob/develop/pom.xml#L55) for the reference to "all-tests"

2. The [Travis file](https://github.com/oceanprotocol/squid-java/blob/develop/.travis.yml#L42) has the integration test commented out AND has the typo above

3. There is one unit test skipped and 4 integration test errors and 2 skipped integration tests.
Unit test results:
```
[WARNING] Tests run: 47, Failures: 0, Errors: 0, Skipped: 1
```

Integration test results:
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AssetsApiIT.query:197 » DDO Unable to search for DDO's: HttpResponse{statusCod...
[ERROR]   AssetsApiIT.search:183 » DDO Unable to search for DDO's: HttpResponse{statusCo...
[ERROR]   TokensApiIT.transfer:54 » Ethereum Unable transfer tokens 1
[ERROR]   AssetsManagerIT.searchAssets:122 » DDO Unable to search for DDO's: HttpRespons...
[INFO] 
[ERROR] Tests run: 31, Failures: 0, Errors: 4, Skipped: 2
```
_NOTE:_ that the SecretStoreApiIT and SecretStoreManagerIT integration tests are skipped may be expected if most users would need otherwise private key material.

## Failure Information (for bugs)

- The fact integration tests are failing was previously reported in #75, but closed on March 14 when Integration tests were [claimed to have been activated]( https://github.com/oceanprotocol/squid-java/commit/20564e3876c10e22de157b6374b63c3acf0af6cc#diff-354f30a63fb0907d4ad57269548329e3)
- HOWEVER Integration tests are [commented out in Travis](https://github.com/oceanprotocol/squid-java/blob/develop/.travis.yml#L42) And even if they were uncommented, the command is incorrect,  it should refer to the target "all-tests" not "all-test"
-  The "all-tests" target is necessary to invoke the `pre-integration-test` goal else integration tests will fail with `[INFO] Skipping JaCoCo execution due to missing execution data file`
- The AssetsApiIT.search failure was filed before, but closed as not reproducable: #80
- End to End testing of all the Squid public API #14 may need to be re-opened.

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. CAUTION this may not be required, but for thoroughness: remove ALL docker containers
`docker rmi --force $(docker images -q)`
2. As the super user remove the user's .ocean directory:
`root@cerise:~# rm -rf /home/tmarble/.ocean/`
3. Start barge
`KEEPER_VERSION=v0.9.0 bash start_ocean.sh --latest --no-pleuston --local-spree-node
`
4. Wait until Keeper has deployed contracts
`while true; do  ls -l ${HOME}/.ocean/keeper-contracts/artifacts/; sleep 5; done
`
5. Update addresses:
`./src/test/resources/scripts/updateConfAddresses.sh
`
6. Run unit and integration tests:
`mvn clean verify -P all-tests -B > all-tests.log 2>&1 &
`
### Possible Solution

Fixing the Travis file will at least run the integration tests.

Fixing failing tests is another matter.

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: `commit 8b7de709c64ecaa26fc05a64958d5eb9c72c50a5 (HEAD -> develop, tag: v0.4.4, origin/develop, origin/HEAD)`
* Java: `openjdk version "11.0.3" 2019-04-16`
* Barge: `3839315cd5d7286c7c3562edf01e9bc8951e8f09 (HEAD -> develop, origin/develop, origin/HEAD)`
* OS: macOS/linux/win: `Linux cerise 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux`

## Failure Logs

[all-tests.log](https://github.com/oceanprotocol/squid-java/files/3081777/all-tests.log)

**Comment by aaitor** [comment]
typo fixed, tests running in travis
